const allProjectsData = [
    {
      id: 1,
      name: 'Mazunte Surf',
      cardImg: 'img/458shots_so.png',
      category: 'Sistema de Gestion de Turnos',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos. Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    {
      id: 2,
      name: 'Simpsonzzapi',
      cardImg: 'img/288shots_so.png',
      category: 'E-Commerce',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    {
      id: 3,
      name: 'My Indoor Control',
      cardImg: 'img/287shots_so.png',
      category: 'Sistema de Control Invernaderos',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    {
      id: 4,
      name: 'Mazunte Surf',
      cardImg: 'img/458shots_so.png',
      category: 'Sistema de Gestion de Turnos',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos. Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    {
      id: 5,
      name: 'Simpsonzzapi',
      cardImg: 'img/288shots_so.png',
      category: 'E-Commerce',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    {
      id: 6,
      name: 'My Indoor Control',
      cardImg: 'img/287shots_so.png',
      category: 'Sistema de Control Invernaderos',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCode: 'https://simpsonzzapi.vercel.app/',
      description: 'Plataforma de compra-venta de tecnología retro. Permite a los usuarios buscar productos, registrarse, publicar sus propios artículos, hacer reservas de compra, crear valoraciones y añadir favoritos.',
      technologies: 'React JavaScript NodeJs ExpressJs MySQL HTML CSS',
    },
    ]