const allProjectsData = [
    {
      id: 1,
      name: 'My Security',
      cardImg: 'img/458shots_so.png',
      category: 'E-Commerce',
      linkWeb: 'https://my-security.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/Trabajo-Final.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/mysecurityAPI.git',
      description: 'Completar',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript HTML CSS',
    },
    {
      id: 2,
      name: 'Tu Casa Inteligente',
      cardImg: 'img/288shots_so.png',
      category: 'Landing Page',
      linkWeb: 'https://tu-casa-inteligente.vercel.app/',
      linkCode: 'https://github.com/WenceslaoGoedelmann/tu-casa-inteligente.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    {
      id: 3,
      name: 'Clima',
      cardImg: 'img/287shots_so.png',
      category: 'Pagina de Clima',
      linkWeb: 'https://clima-rouge.vercel.app/',
      linkCode: 'https://github.com/WenceslaoGoedelmann/clima.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    {
      id: 4,
      name: 'My Cocktail',
      cardImg: 'img/458shots_so.png',
      category: 'Sistema de Gestion de Turnos',
      linkWeb: 'https://my-cocktail-three.vercel.app/',
      linkCode: 'https://github.com/WenceslaoGoedelmann/My-Cocktail.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    ]