const allProjectsData = [
    {
      id: 1,
      name: 'My Security',
      img: 'img/mysecurity/mysecurity.png',
      img1: 'img/mysecurity/mysecurity1.png',
      img2: 'img/mysecurity/mysecurity2.png',
      img3: 'img/mysecurity/mysecurity3.png',
      img4: 'img/mysecurity/mysecurity4.png',
      img5: 'img/mysecurity/mysecurity5.png',
      category: 'E-Commerce',
      linkWeb: 'https://my-security.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/Trabajo-Final.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/mysecurityAPI.git',
      description: 'Completar',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript HTML CSS',
    },
    {
      id: 2,
      name: 'Tu Casa Inteligente',
      img: 'img/tucasainteligente/Tu_casa_inteligente.png',
      img1: 'img/tucasainteligente/tucasainteligente1.png',
      img2: 'img/tucasainteligente/tucasainteligente2.png',
      img3: 'img/tucasainteligente/tucasainteligente3.png',
      img4: 'img/tucasainteligente/tucasainteligente4.png',
      img5: 'img/tucasainteligente/tucasainteligente5.png',
      category: 'Pagina de Servicios',
      linkWeb: 'https://tu-casa-inteligente.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/tu-casa-inteligente.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/tu-casa-inteligente.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    {
      id: 3,
      name: 'Clima',
      img: 'img/clima/clima.png',
      img1: 'img/clima/clima1.png',
      img2: 'img/clima/clima2.png',
      img3: 'img/clima/clima3.png',
      img4: 'img/clima/clima4.png',
      img5: 'img/clima/clima5.png',
      category: 'Pagina de Clima',
      linkWeb: 'https://clima-rouge.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/clima.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/clima.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    {
      id: 4,
      name: 'My Cocktail',
      img: 'img/mycocktail/mycocktail.png',
      img1: 'img/mycocktail/mycocktail1.png',
      img2: 'img/mycocktail/mycocktail2.png',
      img3: 'img/mycocktail/mycocktail3.png',
      img4: 'img/mycocktail/mycocktail4.png',
      img5: 'img/mycocktail/mycocktail5.png',
      category: 'Pagina de Preparacion de Cocktails',
      linkWeb: 'https://my-cocktail-three.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/My-Cocktail.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/My-Cocktail.git',
      description: 'Completar',
      technologies: 'JavaScript HTML CSS',
    },
    ]