const topProjectsData = [
    {
      id: 1,
      name: 'Mazunte Surf',
      img: 'img/mazunte/mazunte_surf.png',
      img1: 'img/mazunte/mazunte1.png',
      img2: 'img/mazunte/mazunte2.png',
      img3: 'img/mazunte/mazunte3.png',
      img4: 'img/mazunte/mazunte4.png',
      img5: 'img/mazunte/mazunte5.png',
      category: 'Sistema de Gestión de Turnos',
      linkWeb: 'https://mazunte-surf.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/mazunteSurf.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/mazunteSurfAPI.git',
      description: 'Página web en donde usuarios registrados podrán solicitar un tuno para una clase de surf. Los turnos son limitados, por lo cual, se realiza una validación de los turnos, para que el usuario pueda visualizar solo los días y horarios disponibles. Por otro lado, el usuario adminstrador cuenta con una sección que le permitirá aceptar o cancelar cada turno solicitado por sus clientes; también podrá filtrar los turnos por día, estado y/o usuario. La página web cuenta con su propia API.',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript Bootstrap HTML CSS',
    },
    {
      id: 2,
      name: 'Simpsonzzapi',
      img: 'img/simpsonzzapi/simpsonzzapi.png',
      img1: 'img/simpsonzzapi/simpsonzzapi1.png',
      img2: 'img/simpsonzzapi/simpsonzzapi2.png',
      img3: 'img/simpsonzzapi/simpsonzzapi3.png',
      img4: 'img/simpsonzzapi/simpsonzzapi4.png',
      img5: 'img/simpsonzzapi/simpsonzzapi5.png',
      category: 'E-Commerce',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/simpsonzzapi.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/simpsonzzapiAPI.git',
      description: 'E-Commerce de venta de comida rápida inspirada en la serie televisiva "Los Simpsons". Los usuarios registrados podrán solicitar pedidos, ver el historial de pedidos, etc. El e-Commerce cuenta con su propia API: "SimpsonzzapiAPI".',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript HTML CSS',
    },
    {
      id: 3,
      name: 'My Indoor Control',
      img: 'img/myindoorcontrol/my_indoor_control_1.png',
      img1: 'img/myindoorcontrol/my_indoor_control_1.png',
      img2: 'img/myindoorcontrol/my_indoor_control_2.png',
      img3: 'img/myindoorcontrol/my_indoor_control_3.jpg',
      img4: 'img/myindoorcontrol/my_indoor_control_4.jpg',
      img5: 'img/myindoorcontrol/my_indoor_control_5.jpg',
      category: 'Sistema de Control de Invernaderos',
      linkWeb: 'https://my-indoor-control.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/My-Indoor-Control.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/My-Indoor-Control.git',
      description: '"My Indoor Control" es un sistema de automatización de invernaderos, el cual permite controlar diferentes variables como horas de luz, tiempo de riego, temperatura y humedad. Mediante una APP-WEB el usuario podrá programar dichas variables. El sistema integra un microcontrolador Arduino. Este proyecto involucró tanto el diseño electrónico y eléctrico, como la programación del microcontrolador Arduino y de la APP-WEB.',
      technologies: 'ArduinoIDE JavaScript HTML CSS',
    }
    ]