const topProjectsData = [
    {
      id: 1,
      name: 'Mazunte Surf',
      img: 'img/mazunte/mazunte_surf.png',
      img1: 'img/mazunte/mazunte1.png',
      img2: 'img/mazunte/mazunte2.png',
      img3: 'img/mazunte/mazunte3.png',
      img4: 'img/mazunte/mazunte4.png',
      img5: 'img/mazunte/mazunte5.png',
      category: 'Sistema de Gestion de Turnos',
      linkWeb: 'https://mazunte-surf.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/mazunteSurf.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/mazunteSurfAPI.git',
      description: 'Completar',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript Bootstrap HTML CSS',
    },
    {
      id: 2,
      name: 'Simpsonzzapi',
      img: 'img/simpsonzzapi/simpsonzzapi.png',
      img1: 'img/simpsonzzapi/simpsonzzapi1.png',
      img2: 'img/simpsonzzapi/simpsonzzapi2.png',
      img3: 'img/simpsonzzapi/simpsonzzapi3.png',
      img4: 'img/simpsonzzapi/simpsonzzapi4.png',
      img5: 'img/simpsonzzapi/simpsonzzapi5.png',
      category: 'E-Commerce',
      linkWeb: 'https://simpsonzzapi.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/simpsonzzapi.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/simpsonzzapiAPI.git',
      description: 'Completar',
      technologies: 'React JavaScript NodeJs NoSQL ExpressJs MongoDB Typescript HTML CSS',
    },
    {
      id: 3,
      name: 'My Indoor Control',
      img: 'img/myindoorcontrol/my_indoor_control_1.png',
      img1: 'img/myindoorcontrol/my_indoor_control_1.png',
      img2: 'img/myindoorcontrol/my_indoor_control_2.png',
      img3: 'img/myindoorcontrol/my_indoor_control_3.jpg',
      img4: 'img/myindoorcontrol/my_indoor_control_4.jpg',
      img5: 'img/myindoorcontrol/my_indoor_control_5.jpg',
      category: 'Sistema de Control Invernaderos',
      linkWeb: 'https://my-indoor-control.vercel.app/',
      linkCodeFront: 'https://github.com/WenceslaoGoedelmann/My-Indoor-Control.git',
      linkCodeBack: 'https://github.com/WenceslaoGoedelmann/My-Indoor-Control.git',
      description: 'Completar',
      technologies: 'ArduinoIDE JavaScript HTML CSS',
    }
    ]